---
# handlers file for dnsmasq

- name: start dnsmasq
  service:
    name: dnsmasq
    state: started

- name: stop dnsmasq
  service:
    name: dnsmasq
    state: stopped

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: reload dnsmasq
  service:
    name: dnsmasq
    state: reloaded
